# Generated by Django 5.2.7 on 2025-10-20 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoYouTube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_video', models.CharField(max_length=50, unique=True)),
                ('id_canal', models.CharField(max_length=50)),
                ('titulo', models.CharField(max_length=200)),
                ('fecha_subida', models.DateField()),
                ('duracion', models.CharField(max_length=20)),
                ('vistas', models.PositiveIntegerField()),
            ],
        ),
    ]
