# Generated by Django 5.2.7 on 2025-10-20 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_video_youtube', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_video', models.CharField(max_length=50, unique=True)),
                ('id_canal', models.CharField(max_length=50)),
                ('titulo', models.CharField(max_length=200)),
                ('fecha_subida', models.DateField()),
                ('duracion', models.DurationField()),
                ('vistas', models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='VideoYouTube',
        ),
    ]
